### ISSUE TITLE
Design Blocks 2.0 🤩

### ISSUE THREAD

**Issue by stefanneculai** [froala/design-blocks#81]
A new version for Design Blocks is coming shortly. Putting together the list of changes that we're working on and we'll update them as the code starts to come in.

- [x] Add secondary color for buttons.
- [x] Use Bootstrap 4 classes
- [x] Update backgrounds.
- [x] Update typography.
- [x] Update icons & photos.
- [ ] Demo templates. Eg.: landing page, pricing page, contact page. #21
- [x] Angular components. #3 
- [x] React components. #2
- [x] VueJS components. #2
- [x] Versioning details https://github.com/froala/design-blocks/issues/6
- [x] Details about using the blocks #16 
- [x] See blocks HTML on the websites https://github.com/froala/design-blocks/issues/58
- [ ] Changelog https://github.com/froala/design-blocks/issues/15

**Comment by m5o** [comment]
Just some more ideas:

* use font-awesome brands for company examples 🍒 https://github.com/froala/design-blocks/pull/72/commits/a08c19acb600f1fdd8b3b919984cbd1449e1fa19
* use bootstrap form markup 🍒https://github.com/froala/design-blocks/pull/72/commits/ef5e94e7d695b418f2566c3ead97c38ab2ce6609
* validate html pages 🍒https://github.com/froala/design-blocks/pull/72/commits/c4456f968fa6bdd20e47e273cf78ce9e3d60d6de
* convert `px` to `rem` 🍒https://github.com/froala/design-blocks/pull/72/commits/7736e9ed9fbd8d6849184630623689068c2d0982
* add text utilities with reset and popular brands 🍒https://github.com/froala/design-blocks/pull/72/commits/ff2266f18360224bb7caa6401f7b94acdcdfa9a7
* setup autoprefixer 🍒https://github.com/froala/design-blocks/pull/72/commits/cb4850e2b8989c9f1551d9b2754d4bd6fdf8c94d

**Comment by stefanneculai** [comment]
We're almost ready for the release. Updates coming tomorrow on the website.
